#!/usr/bin/env node
//
// Skeleton generator: cache-dir → output/skeleton.jsx (or .html, etc).
//
// Reads bridge-agent-payload.json (the post-pipeline enriched form with
// computedCss.full / computedHtml on every node), walks the tree via
// render_node + a target emitter, and writes a complete file the consumer
// can drop in directly.
//
// Usage:
//   node ./scripts/generate_skeleton.mjs <cache-dir> [--target react|html] [--out path]
//
// Examples:
//   node ./scripts/generate_skeleton.mjs ./cache/unknown-file/20-532
//   node ./scripts/generate_skeleton.mjs ./cache/.../20-532 --target react --out ./output/Desktop.jsx

import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

import { renderNode, collectFontFamilies } from './lib/render_node.mjs';
import { reactEmitter } from './lib/emitters/react.mjs';

const __filename = fileURLToPath(import.meta.url);
const __dirname  = path.dirname(__filename);
const SKILL_ROOT = path.resolve(__dirname, '..');

// CSS reset injected at the top of the React file as a string constant the
// consumer can drop into a <style> or normalize step. Same content as
// references/02-css-reset.md.
const CSS_RESET = `*, *::before, *::after { box-sizing: border-box; margin: 0; padding: 0; }
h1, h2, h3, h4, h5, h6, p, button, a, ul, ol, li, dl, dt, dd, figure, blockquote, form, fieldset {
  margin: 0; padding: 0; font: inherit; color: inherit; background: transparent; border: 0;
}
a { text-decoration: none; }
button { cursor: pointer; }
img, svg, video { display: block; max-width: 100%; }
input, textarea, select { font: inherit; color: inherit; background: transparent; border: 0; outline: 0; }
table { border-collapse: collapse; }`;

function parseArgs(argv) {
  const args = { cacheDir: null, target: 'react', out: null };
  const rest = [];
  for (let i = 2; i < argv.length; i += 1) {
    const a = argv[i];
    if (a === '--target') args.target = argv[++i];
    else if (a === '--out') args.out = argv[++i];
    else rest.push(a);
  }
  args.cacheDir = rest[0];
  return args;
}

function usage() {
  console.error(`usage: node ./scripts/generate_skeleton.mjs <cache-dir> [--target react|html] [--out path]
example: node ./scripts/generate_skeleton.mjs ./cache/unknown-file/20-532`);
  process.exit(1);
}

function loadPayload(cacheDir) {
  const p = path.join(cacheDir, 'bridge-agent-payload.json');
  if (!fs.existsSync(p)) {
    console.error(`agent-payload not found: ${p}\nRun figma_pipeline.mjs first.`);
    process.exit(1);
  }
  return JSON.parse(fs.readFileSync(p, 'utf-8'));
}

function buildGoogleFontsLink(families) {
  if (!families || families.length === 0) return '';
  // Conservative weight list — covers most styles. Generator doesn't yet pull
  // exact weights; consumer can narrow later. wght@400;700 is the common case;
  // 500/800/900 added to cover headlines/body in design systems.
  const families_param = families
    .map((f) => `family=${encodeURIComponent(f).replace(/%20/g, '+')}:wght@400;500;600;700;800;900`)
    .join('&');
  return `https://fonts.googleapis.com/css2?${families_param}&display=swap`;
}

function jsStringLiteral(s) {
  return JSON.stringify(s);
}

function camelComponentName(s) {
  // turn "Desktop", "Hero section", "20:532" → DesktopComponent name (PascalCase)
  if (!s) return 'GeneratedScreen';
  const cleaned = s
    .replace(/[^A-Za-z0-9]+/g, ' ')
    .trim()
    .split(/\s+/)
    .map((w) => w.charAt(0).toUpperCase() + w.slice(1).toLowerCase())
    .join('');
  return cleaned || 'GeneratedScreen';
}

function emitReactFile({ payload, body, families, sourceMeta }) {
  const root = payload?.designSnapshot?.root;
  const componentName = camelComponentName(root?.name) || 'GeneratedScreen';
  const fontsLink = buildGoogleFontsLink(families);
  const generatedAt = new Date().toISOString();

  return `// AUTO-GENERATED by skills/figma/scripts/generate_skeleton.mjs
// Source: ${sourceMeta.cacheDir}
// Root nodeId: ${root?.id || ''} | type: ${root?.type || ''} | name: ${jsStringLiteral(root?.name || '')}
// Generated: ${generatedAt}
//
// HOW TO USE
// 1. Copy this file to your React project (or import as-is).
// 2. Inject the CSS reset (RESET_CSS const below) into your global stylesheet
//    OR keep the <style dangerouslySetInnerHTML={{__html: RESET_CSS}}/> tag.
// 3. Add the Google Fonts <link> from FONTS_HREF below to your <head>.
// 4. Customize: rename component, swap semantic tags (div → nav/header/main/footer),
//    add interactivity (onClick / hooks). Do NOT manually re-translate node styles —
//    they were precomputed by the pipeline and are bit-equivalent to Figma intent.
//
// Asset files referenced by background-image: url('./assets/<hash>.<ext>') live
// next to this file's source cache; copy/symlink ./assets to your public dir.

import React from 'react';

export const RESET_CSS = ${jsStringLiteral(CSS_RESET)};

export const FONTS_HREF = ${jsStringLiteral(fontsLink)};

export default function ${componentName}() {
  return (
    <>
      <style dangerouslySetInnerHTML={{ __html: RESET_CSS }} />
      ${body.split('\n').join('\n      ')}
    </>
  );
}
`;
}

function emitHtmlFile({ payload, body, families, sourceMeta }) {
  const root = payload?.designSnapshot?.root;
  const fontsLink = buildGoogleFontsLink(families);
  const generatedAt = new Date().toISOString();

  return `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8" />
<title>${(root?.name || 'Generated').replace(/[<>]/g, '')}</title>
${fontsLink ? `<link rel="preconnect" href="https://fonts.googleapis.com" />
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
<link href="${fontsLink}" rel="stylesheet" />` : ''}
<style>${CSS_RESET}</style>
<!-- AUTO-GENERATED ${generatedAt} from ${sourceMeta.cacheDir} -->
</head>
<body>
${body}
</body>
</html>
`;
}

function main() {
  const args = parseArgs(process.argv);
  if (!args.cacheDir) usage();

  const cacheDir = path.resolve(args.cacheDir);
  if (!fs.existsSync(cacheDir)) {
    console.error(`cache-dir does not exist: ${cacheDir}`);
    process.exit(1);
  }

  const payload = loadPayload(cacheDir);
  const root = payload?.designSnapshot?.root;
  if (!root) {
    console.error('agent-payload has no designSnapshot.root');
    process.exit(1);
  }

  const families = collectFontFamilies(root);

  let body, fileSource, defaultExt;
  switch (args.target) {
    case 'react':
      body = renderNode(root, reactEmitter).value;
      fileSource = emitReactFile({ payload, body, families, sourceMeta: { cacheDir } });
      defaultExt = 'jsx';
      break;
    case 'html': {
      // For HTML target, reuse react renderer but post-process: in HTML the
      // style attr should be a CSS string, not {{}}. The simplest approach for
      // this MVP is to render via reactEmitter and then transform style={{...}}
      // back to style="...". We have a richer dedicated html emitter on the
      // roadmap (v1.1) — this is the lightweight bridge for now.
      const reactBody = renderNode(root, reactEmitter).value;
      body = reactBody
        .replace(/ style=\{\{ ([^}]+) \}\}/g, (_, decls) => {
          // decls is like: padding: "12px", backgroundColor: "#e9ecff"
          const css = decls.split(', ')
            .map((d) => {
              const idx = d.indexOf(':');
              const k = d.slice(0, idx).trim().replace(/^"(.*)"$/, '$1');
              const v = d.slice(idx + 1).trim().replace(/^"(.*)"$/, '$1');
              const cssKey = k.replace(/[A-Z]/g, (c) => '-' + c.toLowerCase());
              return `${cssKey}: ${v}`;
            })
            .join('; ');
          return ` style="${css.replace(/"/g, '&quot;')}"`;
        });
      fileSource = emitHtmlFile({ payload, body, families, sourceMeta: { cacheDir } });
      defaultExt = 'html';
      break;
    }
    default:
      console.error(`unknown --target: ${args.target} (expected: react | html)`);
      process.exit(1);
  }

  const outPath = args.out
    ? path.resolve(args.out)
    : path.resolve(SKILL_ROOT, '..', '..', 'output', `skeleton.${defaultExt}`);
  fs.mkdirSync(path.dirname(outPath), { recursive: true });
  fs.writeFileSync(outPath, fileSource);

  // Stats for the summary line
  const nodeCount = (function count(n) {
    let c = 1;
    for (const k of n.children || []) c += count(k);
    return c;
  })(root);

  console.log(JSON.stringify({
    ok: true,
    target: args.target,
    cacheDir,
    out: outPath,
    bytes: fileSource.length,
    nodes: nodeCount,
    fontFamilies: families,
  }, null, 2));
}

main();
